all:
  children:
    local:
      hosts:
        ${{values.sitename}}:
          ansible_connection: local
          namespace: ${{values.project.replaceAll('component:default/','').replaceAll(r/-project$/g, '')}}
          init:
            siteName: ${{values.sitename}}
          {% if values.linkedsite %}
          links:
            - host: ${{values.linkedsite}}
          {% endif %}
    {% if values.linkedsite %}
    linked:
      hosts:
        ${{values.linkedsite}}:
          ansible_connection: local
    {% endif %}