kind: ConfigMap
apiVersion: v1
metadata:
  name: ${{values.sitename}}-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            ${{values.host}}:
              platform: "podman"
              init:
                siteName: ${{values.sitename}}
                ingressHosts:
                  - ${{values.host}}
              {% if values.linkedsite %}
              links:
                - host: ${{values.linkedsite.replaceAll('component:default/','').replaceAll(r/-skupper-site$/g, '')}}
              {% endif %}
        {% if values.linkedsite %}
        linked:
          hosts:
            ${{values.linkedsite.replaceAll('component:default/','').replaceAll(r/-skupper-site$/g, '')}}:
              ansible_connection: local
        {% endif %}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${{values.sitename}}-skupper-site-init
  namespace: backstage
spec:
  selector: {}
  template:
    metadata:
      name: ${{values.sitename}}-skupper-site-init
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: quay.io/mathianasj/ansible-skupper-pipeline@sha256:9ae7e91a7e65b29038435c804e5dc5d9161b337aba5fbb3d1b2f95c8a1cbce62
          command:
            - ansible-playbook
            - /site-creation.yaml
            - -i
            - /workspace/source/inventory.yml
            - -e
            - vault_url=$(VAULT_URL)
            - --private-key=/workspace/.ssh/id_rsa
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
            - name: ssh
              mountPath: /workspace/.ssh
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: ${{values.sitename}}-inventory
          defaultMode: 420
      - name: ssh
        configMap:
          name: ssh-key
          defaultMode: "0600"
      restartPolicy: Never
