apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${{values.project.replaceAll('component:default/','').replaceAll(r/-project$/g, '')}}
  name: ${{values.name}}
  annotations: {}
spec:
  selector:
    matchLabels:
      app: ${{values.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${{values.name}}
    spec:
      containers:
        - name: container
          image: >-
            ${{values.image}}
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: Recreate
  paused: false

