apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: skupper-rhel-site
  title: RHEL Skupper Site
  description: An skupper site that can be linked to others
  tags:
    - skupper
spec:
  owner: service@example.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - host
        - service
        - port
      properties:
        host:
          title: Host
          type: string
          description: The target RHEL Host IP/DNS Name
        sitename:
          title: Service Name
          type: string
          description: The unique name for the service in the skupper service
        port:
          title: Port
          type: string
          description: The port number for the bound / exposed service
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          host: ${{ parameters.host }}
          sitename: ${{ parameters.sitename }}
          linkedsite: ${{ parameters.linkedsite }}

    - id: pull-request
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
        branchName: ${{ parameters.sitename }}
        title: skupper for ${{ parameters.sitename }}
        description: skupper for ${{ parameters.sitename }}
        
