apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: skupper-exposed-deployment
  title: Expose Deployment
  description: Expose an OpenShift deployment in the skupper network
  tags:
    - skupper
spec:
  owner: service@example.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - service
        - project
        - site
        - deployment
      properties:
        service:
          title: Service Name
          type: string
          description: The name for the exposed service
        project:
          title: Project
          type: string
          description: The target OpenShift project
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - 'spec.type':
                  - ocp-project
        site:
          title: Skupper Site
          type: string
          description: The name for the skupper site.
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - 'spec.type':
                  - skupper-site
        deployment:
          title: Deployment
          type: string
          description: The target deployment to expose via a route
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - 'spec.type':
                  - ocp-deployment
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          project: ${{ parameters.project }}
          sitename: ${{ parameters.sitename }}
          linkedsite: ${{ parameters.linkedsite }}

    - id: pull-request
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
        branchName: ${{ parameters.sitename }}
        title: skupper for ${{ parameters.sitename }}
        description: skupper for ${{ parameters.sitename }}
        
