kind: ConfigMap
apiVersion: v1
metadata:
  name: ${{values.sitename}}-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            ${{values.sitename}}:
              ansible_connection: local
              namespace: ${{values.project.replaceAll('component:default/','').replaceAll(r/-project$/g, '')}}
              init:
                siteName: ${{values.sitename}}
              {% if values.linkedsite %}
              links:
                - host: ${{values.linkedsite.replaceAll('component:default/','').replaceAll(r/-skupper-site$/g, '')}}
              {% endif %}
        {% if values.linkedsite %}
        linked:
          hosts:
            ${{values.linkedsite.replaceAll('component:default/','').replaceAll(r/-skupper-site$/g, '')}}:
              ansible_connection: local
        {% endif %}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${{values.sitename}}-skupper-site-init
  namespace: backstage
spec:
  selector: {}
  template:
    metadata:
      name: ${{values.sitename}}-skupper-site-init
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: quay.io/mathianasj/ansible-skupper-pipeline@sha256:a72ef1d052d661694c47cb46ec2b1be906e778ca5b7946451f87f0e2a78a2172
          command:
            - ansible-playbook
            - /site-creation.yaml
            - -i
            - /workspace/source/inventory.yml
            - -e
            - vault_url=$(VAULT_URL)
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
          env:
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: ${{values.sitename}}-inventory
          defaultMode: 420
      restartPolicy: Never
