apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-baremetal-openshift 
  title: New Baremetal OpenShift Cluster 
  description: New baremetal OpenShift Cluster 
  tags:
    - baremetal
spec:
  owner: Anil Son
  type: system
  
  parameters:
    - title: Provide information for the Baremetal OpenShift Cluster
      required:
        - clustername
        - availabilityzone
      properties:
        clustername:
          title: OpenShift Cluster Name
          type: string
          description: OpenShift Cluster Name
        availabilityzone:
          title: Availability Zone
          type: string
          description: Availability Zone
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          clustername: ${{ parameters.clustername }}
          availabilityzone: ${{ parameters.availabilityzone }}

    - id: pull-request
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=project-repo&owner=ansonmez
        branchName: ${{ parameters.clustername }}
        title: openshift for ${{ parameters.clustername }}
        description: openshift for ${{ parameters.clustername }}
        
