apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: openshift-project
  title: OpenShift Project
  description: An OpenShift project to host applications
  tags:
    - openshift
spec:
  owner: service@example.com
  type: system
  
  parameters:
    - title: Provide information on this application
      required:
        - project
      properties:
        project:
          title: Project
          type: string
          description: The name for the OpenShift project
  steps:
    - id: template-namespaces 
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          project: ${{ parameters.project }}

    - id: pr
      name: make a pr with the new namespaces
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
        branchName: ${{ parameters.project }}-project
        title: Create OpenShift Project ${{ parameters.project }}
        description: Create OpenShift Project ${{ parameters.project }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
        catalogInfoPath: "/catalog/${{values.project}}-project.yaml"

    # - id: pull-request
    #   name: make a pr with the new namespaces
    #   action: publish:github:pull-request
    #   input:
    #     repoUrl: github.com?repo=project-repo&owner=backstage-skupper-demo
    #     branchName: ${{ parameters.sitename }}
    #     title: skupper for ${{ parameters.sitename }}
    #     description: skupper for ${{ parameters.sitename }}
        
